- name: generate .dot data
  set_fact:
    lldp_topo: "{{ lookup('template', 'lldp_topo.dot.j2') }}"
  delegate_to: localhost
  run_once: True 

- name: Grab Current Time
  set_fact: current_time="{{ lookup('pipe','date +%Y-%m-%d\_%H-%M-%S') }}"  
  delegate_to: localhost
  run_once: True 

- name: generate lldp_topo.png
  command: /usr/bin/dot -Tpng -o "{{ repository['path'] }}"/lldp_graphviz/network_maps/lldp_topo_{{current_time}}.png
  args:
    stdin: "{{ lldp_topo }}"
  delegate_to: localhost
  run_once: True 
