---
- name: Gather facts
  hosts: cml_catalyst
  connection: local
  gather_facts: no

  roles:
    - { role: napalm_get_facts , filter: ['facts', 'lldp_neighbors'] } 

- name: Generate LLDP topology graph
  hosts: localhost
  gather_facts: no

  roles:
    - cisco_lldp_topo

