---
- name: Retrieve a repository from a distant location and make it available to the local EE
  ansible.scm.git_retrieve:
    origin:
      url: "https://github.com/andubiel/ansible_cml_demos.git"
    parent_directory: /tmp/
    branch:
      name: main
      duplicate_detection: no
  register: repository
  when: inventory_hostname == 'localhost'

- name: Gather facts
  hosts: cml_catalyst
  gather_facts: no

  roles:
    - { role: napalm_get_facts , filter: ['facts', 'lldp_neighbors'] } 

- name: Generate LLDP topology graph
  hosts: localhost
  gather_facts: no

  roles:
    - cisco_lldp_topo

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ repository['path'] }}"
    token: "{{ password }}"
    user:
      name: "{{ username }}"
      email: "{{ email }}"
  when: inventory_hostname == 'localhost'

