---
- name: Device and service provisioning for cisco devices
  hosts: lab
  connection: network_cli
  gather_facts: no

  roles: 
    - { role: cisco_device_provisioning, tags: ['device'] }
    - { role: cisco_vlan_service, tags: ['service'] }
    - { role: cisco_validate, tags: ['validate'] }
